<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/4/9
 * Time: 18:41
 */

namespace app\admin\model;


use app\osys\service\Omodel;

class Menu extends Omodel
{
    public function cols($item)
    {
        //parent::cols($item); // TODO: Change the autogenerated stub
        $item->col('name')->name('菜单名称')->def("");
        $item->col('title')->name('菜单标题')->def("");
        $item->col('icon')->name('图表样式')->def("");
        $item->col('jump')->name('菜单路由地址')->def("/");
        $item->col('spread')->name('是否默认展开子菜单true/false')->type("tinyint(1)")->def("0");
        $item->col('pid')->name('父级ID')->type("int(11)")->def("0");
        $item->col('sort')->name('排序')->type("int(11)")->def("1");
        $item->col('del')->name('是否删除0：正常，1：删除')->type("tinyint(1)")->def("0");
    }
}