<?php


namespace app\monitor\model;


use app\monitor\model\Omodel;

class DataTotal extends Omodel
{
    public function cols($item)
    {
        //parent::cols($item); // TODO: Change the autogenerated stub
        $item->col('customer_id')->name('客户ID')->def("");
        $item->col('number')->name('接受到的数据量')->type("int(11)")->def(0);
        $item->col('create_time')->name('创建时间')->type("int(11)")->def(0);
        $item->col('complete_time')->name('完成时间')->type("int(11)")->def(0);
        $item->col('time_difference')->name('时间差')->type("int(11)")->def(0);
    }
}